site_name: TabularTransformer
site_url: https://echosprint.github.io/TabularTransformer/
repo_url: https://github.com/echosprint/TabularTransformer
repo_name: echosprint/TabularTransformer

theme:
  name: material
  palette:
    primary: black
    accent: grey
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - content.code.copy
    - search.highlight
    - content.code.select

# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - HyperParameters: hyperparameters.md
  - Embedding: embedding.md
  - FAQ: faq.md

# [Extensions]
plugins:
  - search:
      lang:
        - en
  - tags

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
      auto_title: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  # - footnotes


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/table.css
